In [ ]:
import sys
sys.version

'3.11.13 (main, Jun  4 2025, 08:57:29) [GCC 11.4.0]'

In [ ]:
np._version_

NameError: name 'np' is not defined

In [ ]:
import numpy as np
print(np.__version_

SyntaxError: incomplete input (ipython-input-4-1164129342.py, line 2)

In [ ]:
list=[0,1,2,3,4,5]
list

In [ ]:
type(list)

In [ ]:
arr=np.array(list)
arr

In [ ]:
type(arr)

In [ ]:
arr= np.array(mylist)
arr

NameError: name 'np' is not defined

In [ ]:
import numpy as np
mylist = [1, 2, 3, 4, 5]
arr = np.array(mylist)
print(arr)
print(type(arr))

In [ ]:
np.arange(10)

In [ ]:
np.arange(10,20)

NameError: name 'np' is not defined

In [ ]:
np.arange(10,50,5)

In [ ]:
np.arange(10,30,3)

In [ ]:
np.arange(10,20,5,2)

In [ ]:
np.arange(20,8)

In [ ]:
np.arange(8,20)

In [ ]:
np.arange(-30,8)

In [ ]:
n=np.arange(-30,8)
n

In [ ]:
np.zeros(3)

In [ ]:
np.zeros(3,dtype=int)

NameError: name 'np' is not defined

In [ ]:
z=np.zeros(5)
z

In [ ]:
import numpy as np
z=np.zeros(5)
print(z)

In [ ]:
np.zeros((5,3))

NameError: name 'np' is not defined

In [ ]:
np.zeros((2,2))

In [ ]:
import numpy as np
a = np.array([[0, 0, 0],
              [0, 0, 0],
              [0, 0, 0]])
print(a)

In [ ]:
nd=np.zeros((5,9),dtype=int)
nd

In [ ]:
np.ones(3)

In [ ]:
np.ones((3),dtype=int)

In [ ]:
np.ones((10,10),dtype=int)

NameError: name 'np' is not defined

In [ ]:
nd1=np.ones((10,10),dtype=int)
nd1

In [ ]:
nd1

NameError: name 'nd1' is not defined

In [ ]:
range(5)
r

NameError: name 'r' is not defined

In [ ]:
r = range(5)
print(r)

range(0, 5)


In [ ]:
for i in r:
    print(i)

0
1
2
3
4


In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
range(1,10)

range(1, 10)

In [ ]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [ ]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [ ]:
rand(3,2)

NameError: name 'rand' is not defined

In [ ]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [ ]:
np.random.rand(5)

NameError: name 'np' is not defined

In [ ]:
np.randomrand(2,4)

NameError: name 'np' is not defined

In [ ]:
np.np.random.rand(5)

NameError: name 'np' is not defined

In [ ]:
import numpy as np
np.random.rand(5)

array([0.09075779, 0.60294726, 0.91326814, 0.5694156 , 0.87185504])

In [ ]:
np.random.rand(2,4)

array([[0.15783933, 0.0728925 , 0.1237    , 0.87739407],
       [0.27584038, 0.30794666, 0.00970781, 0.8671964 ]])

In [ ]:
np.random.radint(2,4)

AttributeError: module 'numpy.random' has no attribute 'radint'

In [ ]:
import numpy as np
np.random.randint(2,4)

2

In [ ]:
np.random.radint(10,20,5)

AttributeError: module 'numpy.random' has no attribute 'radint'

In [ ]:
import numpy as np
np.random.radint(10,20,5)


AttributeError: module 'numpy.random' has no attribute 'radint'

In [ ]:
np.random.rand(1,6,4)

array([[[0.28800549, 0.01518508, 0.98570443, 0.90466454],
        [0.52614188, 0.68772811, 0.99764619, 0.51172624],
        [0.53597847, 0.51164792, 0.77782435, 0.41863728],
        [0.5908687 , 0.29659468, 0.94889752, 0.64750213],
        [0.46176514, 0.22972506, 0.33827514, 0.87604005],
        [0.60700853, 0.68875269, 0.08424907, 0.72010035]]])

In [ ]:
np.random.radint(-30,20,10)

AttributeError: module 'numpy.random' has no attribute 'radint'

In [ ]:
import numpy as np

np.random.randint(-30,20,10)


array([  1, -22, -22,  13,  -1,  -3, -23,   7, -15,  -3])

In [ ]:
import numpy as np
np.random.randint(10,40,(10,10))

array([[39, 13, 15, 22, 28, 25, 25, 35, 28, 21],
       [23, 25, 34, 28, 27, 36, 13, 38, 13, 29],
       [28, 19, 21, 15, 11, 33, 12, 32, 38, 24],
       [22, 39, 10, 37, 27, 39, 20, 28, 32, 33],
       [14, 12, 12, 15, 39, 34, 30, 22, 14, 18],
       [27, 19, 33, 24, 17, 10, 12, 35, 14, 27],
       [16, 22, 28, 28, 26, 22, 29, 11, 34, 15],
       [13, 10, 34, 21, 26, 19, 25, 13, 30, 15],
       [21, 12, 39, 38, 17, 23, 27, 29, 30, 11],
       [28, 32, 27, 12, 26, 25, 17, 29, 24, 26]])

In [ ]:
import numpy as np
np.random.randint(1,100,(12,12))

array([[57,  6, 62, 50, 41, 15, 79, 78, 69, 74, 31, 67],
       [32, 55, 42, 42, 24, 63, 93, 51, 97, 65,  3, 80],
       [72, 65, 81,  5, 38, 26, 27,  1,  8, 21, 50, 97],
       [39, 33, 46, 26, 94, 83, 90, 48, 56, 94, 59, 25],
       [62, 24,  1, 26, 51, 30, 54, 20, 12, 46, 95, 16],
       [85, 11, 61, 48, 89, 87, 92, 85, 58, 66, 27, 78],
       [98, 22, 11, 49, 82, 32, 73, 73, 57, 92, 60, 40],
       [62, 97, 61, 54,  8, 11, 11, 77, 43, 19, 55,  9],
       [10, 94,  9, 48, 46, 81,  6, 26, 56, 25, 88, 99],
       [52, 33, 54, 23, 81, 39, 52, 86, 24, 25, 38, 45],
       [77, 54, 93, 53, 86, 93, 62, 90, 37, 59, 26,  2],
       [32, 44, 23, 16, 66, 45, 13, 75, 61, 22, 41, 79]])

In [ ]:
import numpy as np
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [ ]:

np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [ ]:
import numpy as np
b = np.random.radint(10,20, (5,4))
print(b)


AttributeError: module 'numpy.random' has no attribute 'radint'

In [ ]:
np.random.radint(...)

AttributeError: module 'numpy.random' has no attribute 'radint'

In [ ]:
import numpy as np
b = np.random.randint(10,20, (5,4))
print(b)

[[15 11 17 13]
 [10 18 19 10]
 [10 13 10 12]
 [11 11 16 13]
 [12 19 17 13]]


In [ ]:
type(b)

numpy.ndarray

In [ ]:
b

array([[15, 11, 17, 13],
       [10, 18, 19, 10],
       [10, 13, 10, 12],
       [11, 11, 16, 13],
       [12, 19, 17, 13]])

In [ ]:
b[:]

array([[15, 11, 17, 13],
       [10, 18, 19, 10],
       [10, 13, 10, 12],
       [11, 11, 16, 13],
       [12, 19, 17, 13]])

In [ ]:
b[1:3]

array([[10, 18, 19, 10],
       [10, 13, 10, 12]])

In [ ]:
b

array([[15, 11, 17, 13],
       [10, 18, 19, 10],
       [10, 13, 10, 12],
       [11, 11, 16, 13],
       [12, 19, 17, 13]])

In [ ]:
b[1,2]

np.int64(19)

In [ ]:
b[2,1]

np.int64(13)

In [ ]:
b[1,-1]

np.int64(10)

In [ ]:
b[2:3]

array([[10, 13, 10, 12]])

In [ ]:
b[0:-2]

array([[15, 11, 17, 13],
       [10, 18, 19, 10],
       [10, 13, 10, 12]])

In [ ]:
b[0,-2]

np.int64(17)

In [ ]:
b[-5,-3]

np.int64(11)

In [ ]:
import numpy as np
np.random.randint(10,20, (4,4))

array([[16, 13, 16, 16],
       [14, 12, 10, 12],
       [12, 16, 17, 16],
       [16, 10, 15, 15]])

In [ ]:
b[-4,-2]

np.int64(19)

In [ ]:
## Numpy Operations


In [1]:
mat

NameError: name 'mat' is not defined

In [2]:
arr

NameError: name 'arr' is not defined

In [4]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [5]:
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
arr.max()

np.int64(6)

In [7]:
arr.min()

np.int64(1)

In [8]:
  arr.mean()

np.float64(3.5)

In [10]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [11]:
arr.mode()

AttributeError: 'numpy.ndarray' object has no attribute 'mode'

In [12]:
from re import M
from numpy import *
arr = ([1,2,3,4,5,6])
median(arr)

np.float64(3.5)

In [13]:
from numpy import *
arr = ([1,2,3,4,5,6])
median(arr)

np.float64(3.5)

In [17]:
import numpy as np


In [19]:
mat = np.arange(0,100).reshape(10,10)
print(mat)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [20]:
mat[1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
mat[4,5]

np.int64(45)

In [23]:
row = 5
column = 6

In [24]:
mat[:column]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [25]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [26]:
mat[:,column]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [27]:
## To print row
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [28]:
## To print column
mat[:,7]

array([ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97])

In [29]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [30]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [31]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [32]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [33]:
mat[1:2,2:4]

array([[12, 13]])

In [ ]:
## Masking and filter


In [34]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [35]:
mat>50


array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [36]:
mat[mat > 50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [37]:
mat[mat>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [38]:
mat[mat == 60]

array([60])

In [39]:
mat[mat != 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])