In [1]:
# july 3
import sys
sys.version

'3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]'

In [4]:

np._version_


AttributeError: module 'numpy' has no attribute '_version_'

In [5]:
import numpy as np
print(np.__version__)

2.1.3


In [6]:
list=[0,1,2,3,4,5]
list

[0, 1, 2, 3, 4, 5]

In [7]:
type(list)

list

In [8]:
arr=np.array(list)
arr

array([0, 1, 2, 3, 4, 5])

In [2]:
type(arr)

NameError: name 'arr' is not defined

In [4]:
arr= np.array(mylist)
arr

NameError: name 'np' is not defined

In [6]:
import numpy as np
mylist = [1, 2, 3, 4, 5]
arr = np.array(mylist)
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [10]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [11]:
np.arange(10,20,5,2)

TypeError: Cannot interpret '2' as a data type

In [12]:
np.arange(20,8)

array([], dtype=int64)

In [13]:
np.arange(8,20)

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
np.arange(-30,8)

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7])

In [16]:
n=np.arange(-30,8)
n

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7])

In [ ]:
# Zeros


In [17]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [1]:
z=np.zeros(5)
z

NameError: name 'np' is not defined

In [4]:
import numpy as np
z=np.zeros(5)
print(z)

[0. 0. 0. 0. 0.]


In [6]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [8]:
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

NameError: name 'array' is not defined

In [9]:
import numpy as np
a = np.array([[0, 0, 0],
              [0, 0, 0],
              [0, 0, 0]])
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [10]:
nd=np.zeros((5,9),dtype=int)
nd

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3),dtype=int)

array([1, 1, 1])

In [13]:
np.ones((10,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [14]:
nd1=np.ones((10,10),dtype=int)
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [15]:
np.three(3)  # module 'numpy' has no attribute 'three'


AttributeError: module 'numpy' has no attribute 'three'

In [16]:
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])